// <auto-generated />
namespace Code4Cash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_active_property_account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_active_property_account));
        
        string IMigrationMetadata.Id
        {
            get { return "201612041806023_added_active_property_account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
