// <auto-generated />
namespace Code4Cash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class owner_to_booking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(owner_to_booking));
        
        string IMigrationMetadata.Id
        {
            get { return "201612071018070_owner_to_booking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
