// <auto-generated />
namespace Code4Cash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_name_to_meeting : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_name_to_meeting));
        
        string IMigrationMetadata.Id
        {
            get { return "201612021931177_added_name_to_meeting"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
