// <auto-generated />
namespace Code4Cash.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class added_selector : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(added_selector));
        
        string IMigrationMetadata.Id
        {
            get { return "201612022014500_added_selector"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
